image: wearemobedia/core-build:0.0.2
clone:
  depth: 1

pipelines:
  branches:
    master:
      - step:
          script:
            - npm install
            - npm run build
            - s3-website create leafshade-portfolio -u build/ -d
